### PR TITLE
Changed README

### PR DESCRIPTION
**Pull request by jeppard**
# Skiosa - PR
- [ ] added test(s), or explain why one is not needed/possible... < Only Readme Changes
- [x] added comments to all the functions
- [x] added documentation to latex project
- [x] code can't be split up into smaller logical units
- [x] code is formated and linted

### CODE REVIEW

**Comment by jeppard** [comment]
Documentation still missing because ticket [SKIOS-133](https://skiosa.atlassian.net/browse/SKIOS-133) has no user story

**Comment by jeppard** [comment]
Added Documentation; link [here](https://github.com/skiosa/documentation/pull/14)

**Comment by LukasLJL** [comment]
Do we have a ``Service-Lead`` for this repo? Because the AC says the README must contain ``Codeowners``

**Comment by jeppard** [comment]
> Do we have a `Service-Lead` for this repo? Because the AC says the README must contain `Codeowners`

I don't know who it would be because it's not a service

**Review by LukasLJL — APPROVED** [review]
lgtm

**Pull request merged**
